[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
indexmap = { version = "1.8.1", features = ["serde"] }
gloo-storage = "0.2.0"
gloo-net = "0.2.0"
log = "0.4.6"
serde_json = "1.0.79"
wasm-bindgen = "0.2"
wasm-logger = "0.2.0"
web-sys = "0.3"
wee_alloc = "0.4.5"
yew = "0.19.3"
yew-hooks = "0.1.54"
yew-router = "0.16.0"
