[package]
name = "frontend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
yew-hooks = "0.1.54"
yew-router = "0.16.0"
web-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.30"
uuid = { version = "1.0.0", features = ["serde", "js", "v4"] }
gloo-storage = "0.2.0"
gloo-net = "0.2.0"
serde_json = "1.0.79"
log = "0.4.6"
wasm-logger = "0.2.0"
futures = "0.3.21"
common = { path = "../common" }
