[[proxy]]
backend = "http://localhost:3000/api/"

[[proxy]]
backend = "ws://localhost:3000/api/"
ws = true

[[hooks]]
stage = "build"
command = "sh"
command_arguments = [
  "-c",
  "npx tailwindcss -c tailwind.config.js -o $TRUNK_STAGING_DIR/tailwind.css",
]
