[[proxy]]
backend = "http://localhost:3000/api/"

[[proxy]]
backend = "ws://localhost:3000/api/"
ws = true

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = [
  "-c",
  "npx tailwindcss -c tailwind.config.js -o tailwind.css",
]
