[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5.4", features = ["ws", "headers"] }
axum-extra = { version = "0.3.1", features = ["spa"] }
common = { path = "../common" }
futures = "0.3.21"
serde_json = "1.0.79"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.3.0", features = ["fs", "trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.0.0", features = ["serde", "v4"] }
